kind: pipeline
type: kubernetes
name: opencl-linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: opencl-test
    image: diabloxenon/opencl:0.1.0-amd64
    pull: always
    commands:
      - cargo check
      - cargo build --verbose --all
      - cargo test --verbose --all
trigger:
  branch:
    - master
  event:
    - push

---
kind: pipeline
type: kubernetes
name: opencl-linux-arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: opencl-test
    image: diabloxenon/opencl:0.1.0-arm64
    pull: always
    commands:
      - cargo check
      - cargo build --verbose --all
      - cargo test --verbose --all
trigger:
  branch:
    - arm64
  event:
    - push
